edit: serverUDP serverTCP clientUDP clientTCP

serverUDP : serverUDP.c
	gcc -o ../servers/serverUDP serverUDP.c
serverTCP : serverTCP.c
	gcc -o ../servers/serverTCP serverTCP.c
clientUDP : clientUDP.c
	gcc -o ../clients/clientUDP clientUDP.c
clientTCP : clientTCP.c
	gcc -o ../clients/clientTCP clientTCP.c
clean :
	rm ../servers/serverUDP ../servers/serverTCP ../clients/clientUDP ../clients/clientTCP 
